# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions: write-all


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Terraform fmt
        working-directory: cloud/aws
        id: fmt
        run: terraform fmt -check

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          scan-ref: ./cloud/aws
          file-patterns: 'terraform:.*\*.tf:terraform:.*\.tfvars'
          format: 'sarif'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL'
          output: 'results.sarif'


      - name: Upload scanning result
        run: |
          cat results.sarif \
           | jq -r '.runs[].tool[].rules[].fullDescription' >> $GITHUB_STEP_SUMMARY

      - name: print scanning result
        run: |
          cat results.sarif

      #   id: terrascan
      #   uses: tenable/terrascan-action@v1.5.0
      #   with:
      #     iac_type: "terraform"
      #     iac_version: "v14"
      #     policy_type: "aws"
      #     only_warn: true
      #     iac_dir: cloud/aws
      #     sarif_upload: true
      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #       sarif_file: terrascan.sarif