name: Destroy

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  destroy_deployment:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.0.0
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::890504605381:role/Deploy-with-OIDC
          role-session-name: awssession
          mask-aws-account-id: false


      - run: terraform init -backend-config=conf/deployment-backend.tfvars
        working-directory: cloud/aws

      - run: |
          if [[ 'deployment' != $(terraform workspace show) ]]; then
            terraform workspace select deployment || terraform workspace new deployment
          fi
        working-directory: cloud/aws

      - id: destroy_plan
        working-directory: cloud/aws
        run: terraform plan -destroy -no-color -var-file=conf/deployment-variables.tfvars -out destroy-deployment-${{ github.run_id }}.plan

      - name: Terraform Destroy
        working-directory: cloud/aws
        run: |
          terraform apply -destroy  -auto-approve -input=false destroy-deployment-${{ github.run_id }}.plan
